### ISSUE TITLE
CDN download returns 404

### ISSUE THREAD

**Issue by antal-k** [Step7750/node-csgo-cdn#47]
```
(node:60848) [steam-user] Warning: No branch name was specified for app 730, depot 731. Assuming "public".
(Use `node --trace-warnings ...` to show where the warning was created)

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
OperationalError: HTTP error 404
    at ClientRequest.<anonymous> (/Users/-/melo/-/stickers/node_modules/steam-user/components/cdn.js:585:13)
    ... 9 lines matching cause stack trace ...
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  cause: Error: HTTP error 404
      at ClientRequest.<anonymous> (/Users/-/melo/-/stickers/node_modules/steam-user/components/cdn.js:585:13)
      at Object.onceWrapper (node:events:628:26)
      at ClientRequest.emit (node:events:513:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:542:22)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23),
  isOperational: true
}
```

**Comment by antal-k** [comment]
I think it's related to `steam-user` package.

**Comment by wavpro** [comment]
Fixed in pull request #48

**Comment by antal-k** [comment]
thanks @wavpro

**Comment by Flo4604** [comment]
Also make sure the steam-user is on its latest version it will still throw 404 errors otherwise

**Comment by wavpro** [comment]
> Make sure the steam-user is on its latest version it will still throw 404 errors otherwise
> 
> @wavpro Would you mind adding a new commit to adding the .gid to the debug log so there is no object object in the message
> 
> ![image](https://user-images.githubusercontent.com/53355483/244894848-d54967e4-4109-4e5a-b48c-9df95eed16de.png)

Fixed! I've also already fixed it in my fork, cs2-cdn.
